package main

const (
	Catalan             = "ca-es"
	ChineseChina        = "zh-cn"
	ChineseHongKong     = "zh-hk"
	ChineseTaiwan       = "zh-tw"
	Danish              = "da-dk"
	Dutch               = "nl-nl"
	EnglishAustralia    = "en-au"
	EnglishCanada       = "en-ca"
	EnglishGreatBritain = "en-gb"
	EnglishIndia        = "en-in"
	EnglishUnitedStates = "en-us"
	Finnish             = "fi-fi"
	FrenchCanada        = "fr-ca"
	FrenchFrance        = "fr-fr"
	German              = "de-de"
	Italian             = "it-it"
	Japanese            = "ja-jp"
	Korean              = "ko-kr"
	Norwegian           = "nb-no"
	Polish              = "pl-pl"
	PortugueseBrazil    = "pt-br"
	PortuguesePortugal  = "pt-pt"
	Russian             = "ru-ru"
	SpanishMexico       = "es-mx"
	SpanishSpain        = "es-es"
	SwedishSweden       = "sv-se"
)
